# -*- coding: utf-8 -*-
"""
Created on Sat Jun 22 11:21:09 2024

@author: user
"""
import collections
def CountFrequency(Nuc_Seq):
    """Counts the frequency of each nucleotide in a given nucleotide sequence."""
    return dict(collections.Counter(Nuc_Seq))

string = "AATATGCGACGGGGTGGAATATCATCCAAACAAACGCCCGGCAAGTGTCGTGTGCGCTGGAATCTAGTAGGTCTTCAGGCAATATGGCCGTTTCCTCGATCAGACTGACGGAACATCCCAATGAACCACTGTCATTTATTCACGCCGGGATATGGAGTCAAACGTTAAACTAGTTGAGTCCTCCCACACGCGAATGATTCTATTTTGAAGGACATGAAGTGTCGCTTAAAACTTAGGAGCAAGGATAAGGGGCGGATGGGGATGTGATCGTTCGCTGGAGCAGGCGCAACTTCGGCAACAACACCTGTGGATTCGATTCAAAACCCCAATGCATCAATCCAGTCGTGGTTGTAATACGAGCTTTCAGCTGTTGGCTCCTCTCCACGAGACTACACCCCAGAGAAATTTCGTTCTAGGCTAAGTTGGCTCTGCGGTTGTCAGCAATTAGATTGTTCACGGATCCAAGCTTGAATAAGACAAGCTGTCTTGTGCGTGATAGGCTTAGAGTAGCATATCGTTGCTGGGCAAGAGACTTTACTGGAGATGATCCCAGCGGGGTAATGTGTGATTTGTATGCTTGGACCCTCCAACTGTTTTGCCCCCAGTGGTTCCCCCGGCCGCCATCTACGATAATGAGATGAACCCGGCCATTTACGAGCAAGAGCACAGTCGTTGGTCTATGTTACTGCGATCTCTCTCGGGCGTGCGTAACTGCTTGCGGTCATAGATCAGATTATGAGCACGGTGCGCAAGACCGCTAGCAGCGCTCCAACACACTTAACCGGCTTGAGACCAGGTGGAGCGCCTATAGGGCTTTAT"
result = CountFrequency(string)
print(" ".join(str(val) for key, val in result.items()))
