# -*- coding: utf-8 -*-
"""
Created on Sat Oct 26 19:30:41 2024

@author: user
"""

from structures import *

def calcul_monoiso_Mass(string,MonoisoMass_Table):
    """
    Calculate the monoisotopic mass of a given string based on individual element masses.

    Args:
        string (str): A sequence of elements represented by their symbol.
        dictionnary : The monoisotopic mass of each amino aciud

    Returns:
        float: The total monoisotopic mass of the string based on values in the MonoisoMass_Table.
    """
    k = 0
    for i in string:
        k += float(MonoisoMass_Table[i])
    return k

string = "KVHWWYERRMTVDQCEDKFEGITFISYNDQCPVYRLGCDQIILWIMAQWPAAQNKLYSVRMMDCPPVYCQHHMFLSNDCEFEQHIWFHCQWWVIQDSVDCHTSKILHYAAVFAICGDPNQGYHFVYHVFDHERQMECQTHQYLMGNYWWTFAIWNPHKEYSQEDDGRHMFFGILFPQLFRMWKHNCMLDFADRDQHLHMFDKLSLTCIVVTVRPVDNDVPTCIAKRYSLNFTQATVWINAYGNIVISLFTPRRMKLPFRWQIHNLKMQGTYMRRENPWEMPNCPEWMPRNKHGCIFLEPWQFGSFRSPTTFCKDTPCGQAHIAKDRQCEVIQMTDIEMVFLKFDPHLGGQMAFELPFETHSDCMRDSYKTILQSHYFWVFFRTWYNWGYLGVPWAGVHQPWHYARRNFGDDYVPLKTCAPVEASQYSNNPWEETYWFKFYHVPKWHCLHIPYYVNYVWGHYWADGHYWCCQNNDHHICMFKYTTDNMRQTRSGWFPTEATVTPVHSVWPYQEMWTSQYKTMKAPRMCPICCNYLNSCIQLSQLFPTFGRVRHIDYPGKMCRIHYDVVAWTTGDYVSQYNICIPKQDDDIAVHDHDDTPSMAPAIFENCQPMGVHHYMPDSYIQVLQPWMNQMWHHTGVNRTGEQNYYLQQPTTLYMFRMSCDLKSNKGCTEWQAPKCYVACFGKDHSVQYQRHLEVLAFEQGCYSWYSTTTRRYTHTYYHSAEVSYAFCKGPKDRHIARKEALTWQNAATAAHSRPFQVKPRYSYCNSGCGQNCEMANSYPNFLMDIFCESDPTMQVAQLTHSRHPKSIQMYTRQWDDHIKVINPYKSHGLGQWIYDLPKVPRWAVFICRTTNCNMFRHYDPQNCIFAFTFCSYATHPCRSIWIYHNQRLLCKWQSDLVCGIAVTTHYIFTNDKWNYHPLNRPPEIYMQETQKNHYYKNYQVWWTCPNVFPFNTATEDC"

calcul_monoiso_Mass(string,MonoisoMass_Table)
